### ISSUE TITLE
Difficulties to use these intents !!

### ISSUE THREAD

**Issue by vincegre** [tschmidty69/hass-snips-config#2]
I have setup SNIPS with that assistant and setup a basic trigger on it but I get always that error in HA:

`Intent HassTurnOn is being overwritten by <ScriptIntentHandler - HassTurnOn>.`

My config file is this for snips:

```
intent_script:
  HassTurnOn:
    speech:
      type: plain
      text: 'Cest fait'
    action:
      - service: switch.toggle
        data:
          entity_id: switch.salon_suspension
```

Something wrong here ?

Thanks
